### ISSUE TITLE
download dataset

### ISSUE THREAD

**Issue by Thermaloo** [alexklwong/void-dataset#10]
Hi, I am in China. And I can't seem to download the dataset properly using these links:
    https://drive.google.com/open?id=1kZ6ALxCzhQP8Tq1enMyNhjclVNzG8ODA
    https://drive.google.com/open?id=1ys5EwYK6i8yvLcln6Av6GwxOhMGb068m
    https://drive.google.com/open?id=1bTM5eh9wQ4U8p2ANOGbhZqTvDOddFnlI
It can be opened normally through VPN, but cannot be downloaded smoothly. Is there any other way to download it? Thank you!

**Comment by alexklwong** [comment]
Hi, unfortunately those are the only copies we have distributed.

Is there any particular (preferably free) service that can host up to 100GB and tends to work better in China?

If so, I can have someone look into migrating it.

**Comment by Thermaloo** [comment]
Hi, thank you for your prompt reply. In China, we usually use Netdisks to store and share large files. For example, Baidu Netdisk, it is free and the space is large enough. Thank you for your help, if successful, it will be very convenient for people in China who want to access this dataset.

**Comment by Thermaloo** [comment]
Hi, Alex. I just changed several VPNS to try to download again, and now it can download normally.
