### ISSUE TITLE
Can you provide the d435 camera and imu parameters in raw.bag ?

### ISSUE THREAD

**Issue by xiangyudxy** [alexklwong/void-dataset#2]
1. The fx, fy, cx, cy about d435i
2. The na, ng, ba, bg about imu 
3. The transformation matrix between imu and d435i

Thank You

**Comment by muskie82** [comment]
Yes, I also want to know those IMU parameters... I would try other VI-SLAMs on this VOID dataset.

**Comment by alexklwong** [comment]
Sorry for the slow response, I didn't get an email from github for this repo for some odd reason. But I will look into it and provide the numbers soon.

**Comment by alexklwong** [comment]
I added calibration in this commit: https://github.com/alexklwong/void-dataset/compare/calibration. Currently it is in the calibration branch, once I get the okay from the other authors I'll push it to master

**Comment by xiangyudxy** [comment]
> I added calibration in this commit: [4fade33](https://github.com/alexklwong/void-dataset/commit/4fade3351c647505f744339088b93db42dc4e96f). Currently it is in the calibration branch, once I get the okay from the other authors I'll push it to master

Thanks for your reply！

**Comment by muskie82** [comment]
Thank you very much for your reply!

>   "alignment": {
        "t_camera_to_body": [0.056, 0.048, -0.013],
        "w_camera_to_body": [-1.246, 1.178, -1.237]
    },

Does "w_camera_to_body" mean Rodrigues' rotation parameters from the camera to imu (the vector represents rotation axis and its norm is rotation angle)??

**Comment by stephanietsuei** [comment]
@muskie82, yes.
