### ISSUE TITLE
Scale factor of the stored depthmap

### ISSUE THREAD

**Issue by muskie82** [alexklwong/void-dataset#3]
Thank you very much for sharing your work.

In issue #1, you mentioned depth values are in millimeters and need to divide 1000 to get a metric scale, but I think the scale is still incorrect.
For example, in `office0/image/1551915398.6757.png`, the depth value around a room corner is approximately 700~750mm in the stored depth map, but there must be more than 1 meter considering the sofa size. 

![image](https://user-images.githubusercontent.com/15071493/104348778-7a6cff00-5545-11eb-9a46-c78c8044027f.png)

Also, when I visualize `office0/image/1551915398.6757.png` and `office0/image/1551915399.9445.png` as a 3D point cloud using gt depth and absolute pose, I can see a clear misalignment of 2 depth maps which should be coming from the wrong scale factor.

Do you have any idea?

![image](https://user-images.githubusercontent.com/15071493/104349306-1991f680-5546-11eb-8a51-b27f20b0be6d.png)

**Comment by alexklwong** [comment]
This is strange, I am investigating

**Comment by muskie82** [comment]
Maybe I've got the idea.
In `data_util.py` (https://github.com/alexklwong/void-dataset/blob/master/src/data_utils.py#L76), loaded depth data is divided by 256. I guess this is also true to realsense data... the depth map is not in millimeter but x256 meter scale.
After dividing 256, the map I've shown above is reasonably aligned.
![image](https://user-images.githubusercontent.com/15071493/106287272-f4adbb00-6289-11eb-9407-937e592c5f33.png)

**Comment by alexklwong** [comment]
Sorry it took a while to reply. I went through the sequence to see if there was something wrong, but I didn't find anything strange about it. It seems like you've got it working as well.
Just for transparency here is the data processing pipeline we used:

Depth maps were captured by realsense (in millimeters) and aligned to RGB stream based on nearest time stamp and then they were exported and stored as 16 bit .png files using the save_depth function in data_utils.py. To preserve the floating point accuracy, we multiplied them by 256 during the saving process. 

So the loading process using load_depth from data_utils.py by default multiplies the depth map (png) by 256. This should then yield depth in millimeters.

To make sure that we are both on the same page, can you post the steps that you did (e.g. code/library/software) to get the first reconstruction above and what you did differently for the second?
