### ISSUE TITLE
Does this dataset contain infrared frames？

### ISSUE THREAD

**Issue by Laciniata** [alexklwong/void-dataset#7]
Sorry, I did not fully understand all the information contained in this data set, and I wonder whether this dataset contains infrared frames. If so, how should these frames be extracted?

Thanks!

**Comment by alexklwong** [comment]
Hi, this dataset does not contain infrared. It contains images, sparse point cloud (saved as sparse depth maps), camera calibration, inertials and ground truth dense depth. I believe the realsense does use an IR projector somewhere (it may or may not be the model we used), but this may be internal to the sensor (at least I don't recall seeing any output stream when we read the bags).

**Comment by Laciniata** [comment]
> Hi, this dataset does not contain infrared. It contains images, sparse point cloud (saved as sparse depth maps), camera calibration, ine11123rtials and ground truth dense depth. I believe the realsense does use an IR projector somewhere (it may or may not be the model we used), but this may be internal to the sensor (at least I don't recall seeing any output stream when we read the bags).

Thanks for your detailed reply! I basically understand the content of the dataset now.
